import streamlit as st
import pandas as pd
from i18n.translate import t
from config.locations import get_current_scenario_id
from config.scenarios import load_scenario_content
import achievements
import outbreak_logic as jl


def generate_field_briefing(session_state) -> str:
    """
    Generate a professional Field Briefing Note in Markdown format.
    Pulls from decisions, interview_history, and other session data.
    """
    from datetime import datetime

    decisions = session_state.get("decisions", {})
    interview_history = session_state.get("interview_history", {})
    current_day = session_state.get("current_day", 1)

    # Build the markdown document
    md = []

    # Header
    md.append("# FIELD BRIEFING NOTE")
    scenario_config = session_state.get("scenario_config", {}) or {}
    disease = scenario_config.get("disease_name", "Outbreak")
    setting = scenario_config.get("setting_name", "Investigation Area")
    md.append(f"## {disease} Investigation - {setting}")
    md.append(f"**Date:** {datetime.now().strftime('%Y-%m-%d')}")
    md.append(f"**Investigation Day:** {current_day} of 5")
    md.append("")
    md.append("---")
    md.append("")

    # Executive Summary
    md.append("## Executive Summary")
    md.append("")
    final_conclusion = decisions.get("final_conclusion", "Investigation in progress")
    md.append(f"**Conclusion:** {final_conclusion}")
    md.append("")

    # Case Definition
    md.append("## Case Definition")
    md.append("")
    case_def = decisions.get("case_definition_text", "Not yet defined")
    md.append(f"{case_def}")
    md.append("")

    # Hypotheses
    if session_state.get("initial_hypotheses"):
        md.append("## Initial Hypotheses")
        md.append("")
        for i, hyp in enumerate(session_state.get("initial_hypotheses", []), 1):
            md.append(f"{i}. {hyp}")
        md.append("")

    # Study Design
    md.append("## Study Design")
    md.append("")
    study_design = decisions.get("study_design", {})
    study_type = study_design.get("type", "Not selected")
    md.append(f"**Design:** {study_type.replace('_', '-').title()}")
    md.append("")

    # One Health Domains
    exposure_domains = decisions.get("exposure_domains", {})
    if exposure_domains:
        md.append("### One Health Domains Investigated")
        md.append("")
        for domain, selected in exposure_domains.items():
            status = "✓" if selected else "✗"
            label = domain.replace("_", " ").title()
            md.append(f"- [{status}] {label}")
        md.append("")

    # Sample Size
    sample_size = decisions.get("sample_size", {})
    if sample_size:
        md.append("### Sample Size")
        md.append("")
        md.append(f"- **Cases:** {sample_size.get('cases', 'N/A')}")
        md.append(f"- **Controls per case:** {sample_size.get('controls_per_case', 'N/A')}")
        md.append("")

    # Key Findings from Interviews
    if interview_history:
        md.append("## Key Findings from Field Interviews")
        md.append("")
        for npc_key, history in interview_history.items():
            if history:
                md.append(f"### Interview: {npc_key.replace('_', ' ').title()}")
                md.append("")
                # Show first few exchanges
                for i, msg in enumerate(history[:6], 1):
                    role = "Investigator" if msg["role"] == "user" else "Respondent"
                    content = msg["content"][:200] + "..." if len(msg["content"]) > 200 else msg["content"]
                    md.append(f"**{role}:** {content}")
                    md.append("")
                if len(history) > 6:
                    md.append(f"*... {len(history) - 6} more exchanges*")
                    md.append("")

    # Final Diagnosis
    md.append("## Final Diagnosis")
    md.append("")
    final_dx = decisions.get("final_diagnosis", "Not yet determined")
    md.append(f"{final_dx}")
    md.append("")

    # Recommendations
    recommendations = decisions.get("recommendations", [])
    if recommendations:
        md.append("## Recommendations")
        md.append("")
        for i, rec in enumerate(recommendations, 1):
            md.append(f"{i}. {rec}")
        md.append("")

    # Laboratory Results
    if session_state.get("lab_results"):
        md.append("## Laboratory Results Summary")
        md.append("")
        md.append("Laboratory testing was conducted. Results are available in the investigation database.")
        md.append("")

    # Footer
    md.append("---")
    md.append("")
    md.append("*This field briefing note was generated by the FETP Outbreak Simulation System.*")
    md.append("*For official use in training exercises only.*")

    return "\n".join(md)


def view_interventions_and_outcome():
    st.header("Interventions & Outcome")

    # Gate: outcome view should not be accessible until Day 4+
    if st.session_state.get("current_day", 1) < 4:
        st.info(
            "The **Interventions & Outcome** section opens on **Day 4** "
            "once you have collected enough evidence. Continue your "
            "investigation and return later."
        )
        return

    st.markdown("### Final Diagnosis")
    dx = st.text_input(
        "What is your final diagnosis?",
        value=st.session_state.decisions.get("final_diagnosis", ""),
    )
    st.session_state.decisions["final_diagnosis"] = dx

    st.markdown("### Recommendations")

    # Show scenario-specific intervention recommendations
    scenario_id = st.session_state.get("current_scenario", "aes_sidero_valley")
    with st.expander("📚 Evidence-Based Intervention Guide", expanded=False):
        intervention_content = load_scenario_content(scenario_id, "interventions")
        st.markdown(intervention_content)

    rec_text = st.text_area(
        "List your main recommendations:",
        value="\n".join(st.session_state.decisions.get("recommendations", [])),
        height=160,
    )
    st.session_state.decisions["recommendations"] = [
        ln for ln in rec_text.splitlines() if ln.strip()
    ]

    st.markdown("### Final Conclusion")
    conclusion_options = [
        "Investigation ongoing - more data needed",
        "Japanese Encephalitis outbreak confirmed",
        "Other arboviral disease - further testing required",
        "Environmental exposure identified and mitigated",
        "Outbreak contained - surveillance continuing",
        "Custom conclusion"
    ]
    conclusion_choice = st.selectbox(
        "Select your final conclusion:",
        conclusion_options,
        index=conclusion_options.index(st.session_state.decisions.get("final_conclusion", conclusion_options[0])) if st.session_state.decisions.get("final_conclusion") in conclusion_options else 0
    )

    if conclusion_choice == "Custom conclusion":
        custom_conclusion = st.text_input(
            "Enter your custom conclusion:",
            value=st.session_state.decisions.get("final_conclusion", "") if st.session_state.decisions.get("final_conclusion") not in conclusion_options else ""
        )
        st.session_state.decisions["final_conclusion"] = custom_conclusion
    else:
        st.session_state.decisions["final_conclusion"] = conclusion_choice

    # Generate and export Field Briefing Note
    st.markdown("---")
    st.markdown("### Field Briefing Note")
    st.caption("Generate a professional briefing document summarizing your investigation.")

    if st.button("Generate Field Briefing Note", type="primary"):
        with st.spinner("Generating field briefing note..."):
            briefing_md = generate_field_briefing(st.session_state)
            st.session_state.field_briefing_note = briefing_md
        st.success("Field Briefing Note generated! Preview and download below.")

    if st.session_state.get("field_briefing_note"):
        with st.expander("Preview Field Briefing Note", expanded=True):
            st.markdown(st.session_state.field_briefing_note)

        scenario_id = st.session_state.get("current_scenario", "outbreak")
        st.download_button(
            label="Download Field Briefing Note (.md)",
            data=st.session_state.field_briefing_note,
            file_name=f"field_briefing_{scenario_id}_day{st.session_state.current_day}.md",
            mime="text/markdown",
            help="Download the field briefing as a Markdown file"
        )

    st.markdown("---")
    if st.button("Evaluate Outcome", type="primary", use_container_width=True):
        # Inject scenario context for scoring
        st.session_state.decisions["scenario_id"] = st.session_state.get("current_scenario")
        st.session_state.decisions["scenario_config"] = st.session_state.get("scenario_config")
        st.session_state.decisions["_decision_log"] = st.session_state.get("_decision_log", [])
        st.session_state.decisions["_lab_orders"] = st.session_state.get("lab_orders", [])
        st.session_state.decisions["_environment_findings"] = st.session_state.get("environment_findings", [])

        with st.status("Evaluating your investigation...", expanded=True) as status:
            st.write("Analyzing diagnosis accuracy...")
            st.write("Scoring One Health engagement...")
            st.write("Evaluating lab and environmental findings...")
            outcome = jl.evaluate_interventions(
                st.session_state.decisions, st.session_state.interview_history
            )
            st.session_state["_last_outcome"] = outcome
            status.update(label="Evaluation complete!", state="complete")

    # Show outcome if evaluated
    outcome = st.session_state.get("_last_outcome")
    if outcome:
        render_final_scorecard(outcome)


def render_final_scorecard(outcome: dict):
    """Render the 4-tab post-game debrief: Score, Ground Truth, Timeline, Reflection."""
    tab_score, tab_truth, tab_timeline, tab_reflection = st.tabs(
        ["Score", "Ground Truth", "Timeline", "Reflection"]
    )

    with tab_score:
        _render_score_tab(outcome)

    with tab_truth:
        _render_ground_truth_tab()

    with tab_timeline:
        _render_timeline_tab()

    with tab_reflection:
        _render_reflection_tab()


def _render_score_tab(outcome: dict):
    """Original scorecard with tier, badges, and narrative."""
    tier_colors = {
        "excellent": "#10b981",
        "good": "#3b82f6",
        "adequate": "#f59e0b",
        "needs_improvement": "#ef4444",
    }
    tier = outcome.get("tier", "adequate")
    color = tier_colors.get(tier, "#6b7280")
    score = outcome.get("score", 0)
    max_score = outcome.get("max_score", 100)
    lives_saved = outcome.get("lives_saved", 0)

    # Hero banner
    html = f"""
    <div class="score-banner" style="background: linear-gradient(135deg, {color}22, {color}11); border: 2px solid {color};">
        <div class="score-tier-title" style="color: {color};">{outcome.get('tier_title', 'INVESTIGATION COMPLETE')}</div>
        <div class="score-number" style="color: {color};">{score}/{max_score}</div>
        <div class="lives-saved">\u2764\ufe0f Estimated Lives Saved: <b>{lives_saved}</b></div>
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)

    st.markdown(f"> *{outcome.get('tier_narrative', '')}*")

    st.markdown(f"### Outcome: {outcome.get('status', 'Unknown')}")
    st.markdown(f"Projected new cases (next 2 weeks): **{outcome.get('new_cases', '?')}**")

    # Evidence-to-action links
    because = outcome.get("because", [])
    if because:
        st.markdown("### Evidence-to-Action Links")
        for b in because:
            st.markdown(f"""
            <div class="hint-card" style="border-left-color: {color};">
                <div class="hint-text">{b}</div>
            </div>
            """, unsafe_allow_html=True)

    # Factors
    st.markdown("### Investigation Factors")
    for line in outcome.get("outcomes", []):
        st.write(line)

    # Counterfactuals
    counterfactuals = outcome.get("counterfactuals", [])
    if counterfactuals:
        st.markdown("### What If...?")
        for c in counterfactuals:
            st.markdown(f"""
            <div style="background: #fef2f2; border-left: 4px solid #ef4444; border-radius: 8px; padding: 12px; margin: 8px 0; color: #991b1b;">
                <div style="font-style: italic;">{c}</div>
            </div>
            """, unsafe_allow_html=True)

    # Badges
    earned = st.session_state.get("achievements", [])
    st.markdown("### Badges Earned" if earned else "### Badges")
    if not earned:
        st.caption("No badges earned yet.")
    achievements.render_badge_grid(st.session_state)

    # Shareable scorecard
    with st.expander("Copy Scorecard"):
        badge_text = ", ".join(f"{a['emoji']} {a['name']}" for a in earned) if earned else "None"
        scorecard = (
            f"FETP Outbreak Simulation - Final Score\n"
            f"{'=' * 40}\n"
            f"Tier: {outcome.get('tier_title', 'N/A')}\n"
            f"Score: {score}/{max_score}\n"
            f"Lives Saved: {lives_saved}\n"
            f"Projected New Cases: {outcome.get('new_cases', '?')}\n"
            f"Status: {outcome.get('status', 'N/A')}\n"
            f"Badges: {badge_text}\n"
            f"{'=' * 40}\n"
        )
        st.code(scorecard, language="text")


def _render_ground_truth_tab():
    """Show the actual outbreak ground truth for learning."""
    st.subheader("What Actually Happened")

    truth = st.session_state.get("truth", {})
    scenario_config = st.session_state.get("scenario_config", {})

    # True etiology
    disease_name = scenario_config.get("disease_name", "Unknown")
    st.markdown(f"**True Etiology:** {disease_name}")

    # Key transmission routes
    epi_fields = scenario_config.get("epi_link_fields", [])
    if epi_fields:
        st.markdown("**Key Transmission/Exposure Routes:**")
        for field in epi_fields:
            st.markdown(f"- **{field.get('label', '')}**: {field.get('description', '')}")

    # True case count
    individuals = truth.get("individuals")
    if individuals is not None:
        from data_utils.case_definition import get_symptomatic_column
        sym_col = get_symptomatic_column(truth)
        if sym_col in individuals.columns:
            true_cases = individuals[individuals[sym_col] == True]
            total_pop = len(individuals)
            st.metric("True Cases", f"{len(true_cases)} / {total_pop}")

    # True epi curve
    if individuals is not None:
        from data_utils.charts import make_epi_curve
        st.markdown("### True Epidemic Curve")
        try:
            epi_fig = make_epi_curve(truth)
            st.plotly_chart(epi_fig, use_container_width=True)
        except Exception:
            st.caption("Could not generate epi curve from truth data.")

    # Correct study design
    recommended = scenario_config.get("study_design", {})
    if recommended:
        rec_type = recommended.get("recommended_type", "")
        if rec_type:
            st.markdown(f"**Recommended Study Design:** {rec_type}")


def _render_timeline_tab():
    """Show the player's investigation timeline."""
    st.subheader("Your Investigation Timeline")

    decision_log = st.session_state.get("_decision_log", [])

    if not decision_log:
        st.info("No actions were logged during this investigation.")
        return

    for day in range(1, 6):
        day_events = [e for e in decision_log if e.get("game_day") == day]
        if not day_events:
            continue

        time_spent = sum(e.get("cost_time", 0) for e in day_events)
        budget_spent = sum(e.get("cost_budget", 0) for e in day_events)

        with st.expander(f"Day {day} ({len(day_events)} actions, {time_spent}h, ${budget_spent})", expanded=(day == st.session_state.current_day)):
            for event in day_events:
                event_type = event.get("type", "unknown")
                details = event.get("details", {})
                location = event.get("location_id", "")

                icon = {
                    "interview": "💬",
                    "lab_test": "🔬",
                    "travel": "🚶",
                    "questionnaire_submitted": "📋",
                    "analysis_confirmed": "📊",
                    "recommendations_submitted": "📝",
                }.get(event_type, "▪️")

                desc = details.get("description", event_type)
                if location:
                    desc += f" ({location})"

                cost_parts = []
                if event.get("cost_time", 0) > 0:
                    cost_parts.append(f"{event['cost_time']}h")
                if event.get("cost_budget", 0) > 0:
                    cost_parts.append(f"${event['cost_budget']}")
                cost_str = f" [{', '.join(cost_parts)}]" if cost_parts else ""

                st.markdown(f"{icon} {desc}{cost_str}")


def _render_reflection_tab():
    """Missed clues and structured reflection prompts."""
    st.subheader("Missed Clues")

    npc_truth = st.session_state.get("truth", {}).get("npc_truth", {})
    interview_history = st.session_state.get("interview_history", {})
    revealed_clues = st.session_state.get("revealed_clues", {})

    # Show NPCs not interviewed
    uninterviewed = []
    for npc_key, npc_data in npc_truth.items():
        if npc_key not in interview_history:
            uninterviewed.append((npc_key, npc_data))

    if uninterviewed:
        st.warning(f"You never interviewed {len(uninterviewed)} NPC(s):")
        for npc_key, npc_data in uninterviewed:
            name = npc_data.get("name", npc_key)
            role = npc_data.get("role", "")
            always_reveal = npc_data.get("always_reveal", [])
            with st.expander(f"{name} ({role}) - {len(always_reveal)} clues available"):
                for clue in always_reveal[:5]:
                    st.markdown(f"- {clue}")
                if len(always_reveal) > 5:
                    st.caption(f"...and {len(always_reveal) - 5} more")

    # Show missed clues from interviewed NPCs
    interviewed_with_missed = []
    for npc_key in interview_history:
        npc_data = npc_truth.get(npc_key, {})
        all_clues = set(npc_data.get("always_reveal", []))
        revealed = set(revealed_clues.get(npc_key, []))
        missed = all_clues - revealed
        if missed:
            interviewed_with_missed.append((npc_key, npc_data, missed))

    if interviewed_with_missed:
        st.markdown("### Clues You Missed from Interviewed NPCs")
        for npc_key, npc_data, missed in interviewed_with_missed:
            name = npc_data.get("name", npc_key)
            with st.expander(f"{name} ({len(missed)} missed)"):
                for clue in list(missed)[:5]:
                    st.markdown(f"- {clue}")

    # Reflection prompts
    st.markdown("---")
    st.subheader("Reflection")
    st.caption("Take a moment to reflect on your investigation. These prompts can guide a debrief discussion.")

    prompts = [
        "What was the most critical decision point in your investigation?",
        "If you could go back to Day 1, what would you do differently?",
        "How did the One Health perspective (animal, environmental, human) change your understanding?",
        "What evidence was most convincing for your final diagnosis?",
        "What was the biggest challenge you faced during the investigation?",
    ]
    for i, prompt in enumerate(prompts):
        st.text_area(prompt, key=f"reflection_{i}", height=80)
